name = "kdtree2"
author = "Matthew B. Kennel"
license = "AFL-1.1"
copyright = "Copyright 2004 Matthew Kennel, Institute for Nonlinear Science"
maintainer = "ivan.pribec@gmail.com"

[library]
source-dir = "src"

[[test]]
name = "kdtree2_benchmark"
source-dir = "tests"
main = "kdtree2_benchmark.f90"

[[test]]
name = "kdtree2_test"
source-dir = "tests"
main = "kdtree2_test.f90"